### ISSUE TITLE
fetch failed error in generateHash function

### ISSUE THREAD

**Issue by MrEthical06** [consumet/consumet.ts#440]
### Describe the bug

TypeError: fetch failed     at Object.fetch (node:internal/deps/undici/undici:11730:11)     at processTicksAndRejections (node:internal/process/task_queues:95:5)     at runNextTicks (node:internal/process/task_queues:64:3)     at processImmediate (node:internal/timers:447:9)     at async generateHash (/root/api/node_modules/@consumet/extensions/src/utils/utils.ts:161:20) {   cause: ConnectTimeoutError: Connect Timeout Error       at onConnectTimeout (node:internal/deps/undici/undici:6869:28)       at node:internal/deps/undici/undici:6825:50       at Immediate._onImmediate (node:internal/deps/undici/undici:6857:13)       at processImmediate (node:internal/timers:476:21) {     code: 'UND_ERR_CONNECT_TIMEOUT'   } }

### Steps to reproduce

Dont know when it occurs. i believe its when using anilist routes

### Expected behavior

This should not happen and all endpoints should work fine. 

### Actual behavior

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at processImmediate (node:internal/timers:447:9)
    at async generateHash (/root/api/node_modules/@consumet/extensions/src/utils/utils.ts:161:20) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:6869:28)
      at node:internal/deps/undici/undici:6825:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:6857:13)
      at processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
} this error is shown and the process is killed

**Comment by riimuru** [comment]
@MrEthical06 I have removed blurhash for now, it should be working fine now. Thank you!
