### ISSUE TITLE
Import #7 module="wbg" function="__wbindgen_number_get" error: function import requires a callable

### ISSUE THREAD

**Issue by khysokhorn** [consumet/consumet.ts#610]
### Describe the bug

When movie source we get this error with every extractor 

### Steps to reproduce

> jest ./test/movies/sflix.test.ts

  console.log
    [LinkError: WebAssembly.instantiate(): Import #7 module="wbg" function="__wbindgen_number_get" error: function import requires a callable] err

      at SFlix.fetchEpisodeSources (src/providers/movies/sflix.ts:258:15)

 FAIL  test/movies/sflix.test.ts
  ✕ returns a filled object of streaming sources (2064 ms)

  ● returns a filled object of streaming sources

    WebAssembly.instantiate(): Import #7 module="wbg" function="__wbindgen_number_get" error: function import requires a callable

      257 |     } catch (err) {
      258 |       console.log(err, 'err');
    > 259 |       throw new Error((err as Error).message);
          |             ^
      260 |     }
      261 |   };
      262 |

      at SFlix.fetchEpisodeSources (src/providers/movies/sflix.ts:259:13)
      at async Object.<anonymous> (test/movies/sflix.test.ts:33:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.095 s
Ran all test suites matching /.\/test\/movies\/sflix.test.ts/i.

### Expected behavior

> jest ./test/movies/sflix.test.ts

  console.log
    [LinkError: WebAssembly.instantiate(): Import #7 module="wbg" function="__wbindgen_number_get" error: function import requires a callable] err

      at SFlix.fetchEpisodeSources (src/providers/movies/sflix.ts:258:15)

 FAIL  test/movies/sflix.test.ts
  ✕ returns a filled object of streaming sources (2064 ms)

  ● returns a filled object of streaming sources

    WebAssembly.instantiate(): Import #7 module="wbg" function="__wbindgen_number_get" error: function import requires a callable

      257 |     } catch (err) {
      258 |       console.log(err, 'err');
    > 259 |       throw new Error((err as Error).message);
          |             ^
      260 |     }
      261 |   };
      262 |

      at SFlix.fetchEpisodeSources (src/providers/movies/sflix.ts:259:13)
      at async Object.<anonymous> (test/movies/sflix.test.ts:33:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.095 s
Ran all test suites matching /.\/test\/movies\/sflix.test.ts/i.

### Actual behavior

Should return m3u8

**Comment by wanwanvxt** [comment]
I also got this bug for the past few days. 😥

**Comment by JayadityaGit** [comment]
Same need help on this one !

**Comment by khysokhorn** [comment]
Thanks Stale, Now everything working fine.
